### ISSUE TITLE
Needs new maintainer

### ISSUE THREAD

**Issue by josh** [josh/useragent#100]
I don't quite have the time to maintain this gem any longer.

Looking for someone to take this gem over. If multiple people want to do it thats fine.

## Whats expected

You can do whatever you'd like, but I'd ask that you just consider compatibility of people already using the library. If you're looking to do something crazy different, probably just make a new project. Follow http://semver.org when making version changes.

## What would happen

* I'll give you gem publish access `gem owner useragent --add your@email`
* I'll remove my gem publishing privileges
* Your fork will be made the new network root
* All PRs and Issues will be closed here

## Possible candidates

People who already contributed or had good ideas.

@arches @phocke @qrush @craic @terryfinn @bartimaeus @gshutler @jzajpt @andrewwillis @postmodern

**Comment by gshutler** [comment]
I'll put my hat in the ring. Happy to work with other people if others want to help.

If other people want to be involved then I propose creating an organization to host the root repo (`useragent-rb` appears free).

@josh, would it be possible for whoever takes over to have commit access to this repository for a short time? Whilst people can easily recreate issues in another repo it would probably be easier to merge any good PRs here.

**Comment by josh** [comment]
Alright, @gshutler you're the new network root.
