### ISSUE TITLE
Opera versions after 15 need different detection pattern

### ISSUE THREAD

**Issue by yourtallness** [josh/useragent#72]
Hello,

Opera versions after 15 do not follow the same UA Information pattern as before.

Change in UA Information scheme is confirmed by Opera themselves:
http://my.opera.com/ODIN/blog/2013/07/15/opera-user-agent-strings-opera-15-and-beyond

Since the project has moved to Chromium, it may be of interest to discern between pre-15 and post-15 Opera versions.

Please close this issue if it is deemed to be a duplicate of the following issue (which was not resolved):
https://github.com/josh/useragent/pull/57

Thank you in advance.

**Comment by gshutler** [comment]
Resolved by #97
