### ISSUE TITLE
opera 22.0 is being identified as chrome

### ISSUE THREAD

**Issue by sleung-ttc** [josh/useragent#86]
> navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36 OPR/22.0.1471.70"

**Comment by pkuczynski** [comment]
The same for Opera 26:

````Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60````

**Comment by pkuczynski** [comment]
Solved my issue by switching over to ````browser``` gem in version 0.8.0

**Comment by gshutler** [comment]
Resolved by #97
