### ISSUE TITLE
Android Nexus 5 - platform method returning "Linux"

### ISSUE THREAD

**Issue by kurtfunai** [josh/useragent#91]
First off, thanks for the gem, it is really handy!

I seem to be running into an issue on Android devices where `user_agent.platform` returns `Linux` as the platform instead of `Android`. 

I originally was testing using the Chrome device emulation tool, but after noticing the problem, I tested with an Android Nexus 5 and confirmed that it was returning the same values.

Example:
When viewing with a Nexus 5, here is a list of methods and their return values.
- browser: Chrome
- version: 38.0.2125.102
- platform: Linux

In the `comment` array for user_agent, it does have Android listed, but it is not being returned:
```ruby
comment:
  - Linux
  - Android 4.4.4
  - Nexus 5 Build/KTU84P
```

**Comment by dennisvandehoef** [comment]
@jakswa why not make a pull request with your fix?

**Comment by jakswa** [comment]
@dennisvandehoef thanks for the suggestion, I opened a PR for it, and explained my original hesitations.
